kind = "web"
previewPath = "/"
title = "Buyurtma Boshqaruv Tizimi"
version = "1.0.0"
id = "artifacts/order-system"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19265

[services.development]
run = "pnpm --filter @workspace/order-system run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/order-system", "run", "build" ]
publicDir = "artifacts/order-system/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19265"
BASE_PATH = "/"
